# Generated by Django 6.1.1 on 2026-09-21 14:19

import railway.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_alter_station_latitude_alter_station_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='image',
            field=models.ImageField(null=True, upload_to=railway.models.image_file_path),
        ),
        migrations.AddField(
            model_name='traintype',
            name='image',
            field=models.ImageField(null=True, upload_to=railway.models.image_file_path),
        ),
    ]
